spring:
  data:
    mongodb:
      # host : ip address -> ec2 name으로
      host: i11a808.p.ssafy.io

  ai:
    openai:
      url : "https://api.openai.com/v1/chat/completions"

resttemplate:
  connection:
    timeout: 5000
  read:
    timeout: 5000

bareun:
  url: "http://i11a808.p.ssafy.io:5757/bareun/api/v1/analyze"