spring:
  data:
    mongodb:
      uri: mongodb://ssafy:ssafy@i11a808.p.ssafy.io:27017/kidwe

  ai:
    openai:
      api-key: "sk-qZXVNo6LvuaFwpmrS6IjnoXw9brInxVlwvtRh2MtDsT3BlbkFJOABm6kbNBmfMjzaACTXPxnpE2XiN3ZYpnNCLMj6a0A"
      url : "https://api.openai.com/v1/chat/completions"

resttemplate:
  connection:
    timeout: 3000
  read:
    timeout: 3000

prompt:
  dailynote:
    previous: "나는 "
    post: "안녕"