spring:
  data:
    mongodb:
      host: 43.203.245.97
      port: 27017
      authentication-database: admin
      username: ssafy
      password: ssafy
      database: kidwe

  ai:
    openai:
      api-key: "sk-qZXVNo6LvuaFwpmrS6IjnoXw9brInxVlwvtRh2MtDsT3BlbkFJOABm6kbNBmfMjzaACTXPxnpE2XiN3ZYpnNCLMj6a0A"
      url : "https://api.openai.com/v1/chat/completions"

resttemplate:
  connection:
    timeout: 3000
  read:
    timeout: 3000

bareun:
  host: "i11a808.p.ssafy.io"
  api-key: "koba-ZARQV7A-HRKUDOY-V6U7LJY-YEE7ZFI"