spring:
  datasource:
    url: jdbc:mysql://i11a808.p.ssafy.io:3306/yellowhat
    username: root
    password: ssafy
  data:
    mongodb:
      uri: mongodb://i11a808.p.ssafy.io:27017/yellowhat
  jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true



logging.level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
