spring:
  jackson:
    date-format: HH:mm:ss
  application:
    name: kidwe

  datasource:
    url: jdbc:mysql://i11a808.p.ssafy.io:3307/kidwe
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          format_sql: true
    show-sql: true

  data:
    redis:
      host: i11a808.p.ssafy.io
      port: 6379
      password: ssafy

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  token:
    header: Authorization
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    access-expired-time: 1800000 #30m
    refresh-expired-time: 1209600000 #14d

aws:
  s3:
    bucket-name: common-kidwe
    region:  ap-northeast-2
  cloudfront:
    distribution-url: https://d175w2yu39lrw9.cloudfront.net
  credentials:
    access-key-id: AKIA4MTWI3VOFP4MKQUH
    secret-access-key: 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

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha