spring:
  datasource:
    url: jdbc:mysql://i11a808.p.ssafy.io:3306/yellowhat
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: mongodb://i11a808.p.ssafy.io:27017/yellowhat

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
